/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 Tree_1.gltf --t 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Tree1_1: THREE.Mesh
    Tree1_2: THREE.Mesh
  }
  materials: {
    Tree_wood: THREE.MeshStandardMaterial
    Tree_leaves: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Tree_1.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Tree1_1.geometry} material={materials.Tree_wood} />
        <mesh geometry={nodes.Tree1_2.geometry} material={materials.Tree_leaves} />
      </group>
    </group>
  )
}

useGLTF.preload('/Tree_1.gltf')
