/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 scene.gltf --t 
Author: caseyhameljames (https://sketchfab.com/caseyhameljames)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wumpa-fruit-058451af54264f028c5c297e9d45eaa3
Title: Wumpa Fruit
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube_0: THREE.Mesh
    Cube001_0: THREE.Mesh
    Plane_0: THREE.Mesh
    Plane001_0: THREE.Mesh
    Plane002_0: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Cube_0.geometry}
          material={materials.Material}
          position={[0.37, 0, -0.26]}
          scale={2.803}
        />
        <mesh
          geometry={nodes.Cube001_0.geometry}
          material={materials['Material.001']}
          position={[0.361, -0.073, 2.003]}
          rotation={[0, 0.114, 0]}
          scale={0.213}
        />
        <mesh
          geometry={nodes.Plane_0.geometry}
          material={materials['Material.003']}
          position={[-1.198, -0.326, 2.934]}
        />
        <mesh
          geometry={nodes.Plane001_0.geometry}
          material={materials['Material.004']}
          position={[2.198, 0.349, 2.774]}
          rotation={[-0.049, 0.195, -3.012]}
        />
        <mesh
          geometry={nodes.Plane002_0.geometry}
          material={materials['Material.004']}
          position={[-0.289, 0.927, 3.21]}
          rotation={[0.425, -0.346, -1.313]}
          scale={0.858}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
