export { default as Log } from './Log'
export { default as SmallTree } from './SmallTree'
export { default as MediumTree } from './MediumTree'
export { default as BigTree } from './BigTree'
export { default as Fruit } from './Fruit'
