export { default as Home } from '@/pages/Home'
export { default as LoginPage } from '@/pages/LoginPage'
export { default as OauthRedirectPage } from '@/pages/OauthRedirectPage'
export { default as MainPage } from '@/pages/MainPage'
export { default as SignUpPage } from '@/pages/SignUpPage'
